#cloud-config

write_files:
# setup script
  - path: "/root/setup.preflight.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_preflight_sh_content}
  - path: "/root/setup.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_template_sh_content}
  - path: "/root/deploy.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${deploy_template_content}
  - path: "/root/catalogue.sql"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${catalogue_sql_template_content}
  - path: "/root/kind-multinode.yaml"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${kind_multinode_yaml_content}
  - path: "/root/kind.env"
    permissions: "0777"
    content: |
      MOCK_MODE=${mock_mode}
      NODE_ENV=production
      CATALOGUE_PORT=${catalogue_port}
      CATALOGUE_URL=http://localhost:${catalogue_port}
      OADB_USER=catalogue_user
      OADB_PW='${catalogue_password}'
      OADB_SERVICE=${db_name}_tp
      STATIC_MEDIA_URL=${assets_url}
      DEPLOY_ID=${deploy_id}
      REGION_ID=${region_id}
      OBJECT_NAMESPACE=${object_namespace}
      AWSSECRETACCESSKEY=${s3_secret}
      AWSACCESSKEYID=${s3_key_id}

runcmd:
 - echo "Running prep scripts..."
 - /root/setup.preflight.sh
 - echo "Finished prep scripts."
 - echo "App is starting as kind stack..."

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init-output.log'}