# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - containerPath: /opt/local-path-provisioner
    hostPath: /home/kind
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp
- role: worker
  extraMounts:
  - containerPath: /opt/local-path-provisioner
    hostPath: /home/kind
- role: worker
  extraMounts:
  - containerPath: /opt/local-path-provisioner
    hostPath: /home/kind
- role: worker
  extraMounts:
  - containerPath: /opt/local-path-provisioner
    hostPath: /home/kind

